### ISSUE TITLE
Throwing Error on <a> Clicks

### ISSUE THREAD

**Issue by arist0tl3** [okgrow/auto-analytics#13] opened 2017-10-13 00:28 UTC
Hey all,

seeing a new console error upon updating past 1.0.0, whenever an `<a>` tag is clicked that doesn't actually href the user to a new location:

![image](https://user-images.githubusercontent.com/9328541/31525049-660f195c-af72-11e7-963d-575e383e2f80.png)

Relates to this piece of code: https://github.com/okgrow/auto-analytics/blob/81bd954507f8c25c10a8c55f5d3074b3774f7f46/src/index.js#L73

Looks like there the state is set to null when the default hyperlink isn't routed.

I can submit a PR to guard against an unset state, but figured I'd check here first to see if there would be anything in particular to return instead.

Thanks!

**Comment by cfnelson** [comment] 2017-10-13 02:07
@arist0tl3 Thanks for reporting this! Could you provide a few more details on how the error occurred and the use case?

Is this occurring on the first page load to your website or have you navigated from another page on your site before landing on the page where you click on a `<a>`? 

I will need to double check the html spec for the expected behaviour of `document.referrer` in this case but I will image it would be an empty string or the original `document.referrer`. 

I suspect this would depend on the use case of how the `<a>` is being used.  Would be happy to accept a PR, would like to make sure we handle this in a spec compliant manner if possible.

**Comment by arist0tl3** [comment] 2017-10-13 02:20
@cfnelson No worries.

We aren't necessarily always using anchor tags correctly, so this could be an edge case we'd just need to build around:

```
<a href="#" class="js-switch-tab" data-target="contactus">Contact Us</a>
```

The error occurs onclick for any anchor that is used like this.

**Comment by cfnelson** [comment] 2017-10-13 02:22
@arist0tl3 To confirm you have installed `@okgrow/auto-analytics@1.0.3`? Could you also advise what router you are using? I am attempting to reproduce the bug myself.

**Comment by arist0tl3** [comment] 2017-10-13 02:24
@cfnelson 

Yes, it occurred in 1.0.2 and 1.0.3. We are using [this fork](https://github.com/VeliovGroup/flow-router) of flow router.

**Comment by cfnelson** [comment] 2017-10-13 02:32
@arist0tl3 Would you be able to reproduce this with the example [here](https://github.com/okgrow/auto-analytics/tree/master/examples/react-router) in auto-analytics.

I have so far been unable to reproduce the behaviour myself by adding `<a>` tags to the `client/main.js`. I have attempted to trigger the error with the below `<a>` and have had no luck in producing the TypeError.
```
<a href="/three" >three</a>
<a href="/three#helo" >hey</a>
<a href="">empty</a>
<a href="#">empty hash</a>
<a href="/#">/ hash</a>
```

**Comment by arist0tl3** [comment] 2017-10-13 02:37
@cfnelson I'm on my non-work laptop right now, but I'll try to repro this later tonight or tomorrow. It's a pretty big app, so there's always the possibility of other packages/compatibility code creating an issue.

It's a private repo; otherwise I'd share.

Thanks for looking into this!

**Comment by cfnelson** [comment] 2017-10-13 02:50
@arist0tl3 No problems, I will be curious to hear any updates. I asked regarding the router as I have previously (before switching to React Router) experienced a few obscure, nasty & unexpected behaviours/bugs due to Flow Router and `<a>` tags. I will see if I can reproduce the bug in a Flow Router app.

**Comment by cfnelson** [comment] 2017-10-13 03:17
@arist0tl3 I can reproduce the bug in using `kadira:flow-router@2.12.1` with these two `<a>` tags:
```html
<a href="#">empty hash</a>
<a href="/three#hello">hello</a>
```
But was unable to reproduce the error with the below `<a>` tag:
```html
<a href="/#">/ hash</a>
```
I also attempted to reproduce the bug with `Iron Router` and was unable to! 😂  I am confident now in believing that this behaviour is specific to Flow Router's implementation and is most likely a bug on their end.

I am now unsure if we should be responsible for handling a specific edge case caused by Flow Router. Though if the fix is simple and clear then we would lean towards accepting a PR.

Thanks to you reporting this oddity 🎉 , I also noticed we are being non spec compliant with our implementation of referrer. We are leaving the `#` on the URI which as far as I understand is non spec compliant. Will be needing to fix this as well. 👍

**Comment by arist0tl3** [comment] 2017-10-13 03:43
@cfnelson 

Thanks for looking into this more deeply. I've been working with FR since it came out, so I will take a closer look and see if I can't open a PR against that repo.

**Comment by cfnelson** [comment] 2017-10-13 04:21
@arist0tl3  Would be interested to hear/see the results of your investigation. And potentially we may be ok to include a fix here to handle the TypeError.

If you needed a small demo app to reproduce it in you can use the flow router one we have [here](https://github.com/okgrow/analytics/tree/master/examples/flow-router).

**Comment by arist0tl3** [comment] 2017-10-13 22:35
@cfnelson Took another look at this, and I think that `e.preventDefault` is really the solution here (which I wasn't using in the instances where I was seeing this error). Seems like in not using that when executing actions against `<a>` elements, the `window.history` is just getting polluted.

I think writing around this in either repo (here or FlowRouter) is probably encouraging sloppy handling of `<a>`, which is exactly what brought me here. If you think there is another solution, let me know if I can help in any way =)

**Comment by cfnelson** [comment] 2017-10-16 18:36
@arist0tl3 Thanks for the update. If `Flow Router` is polluting the `window.history` then I would imagine it should be their responsibility. Out of curiosity how/what are they doing to `window.history`?

Maybe for the time being we can edit the title of this Issue to include a mention that this is a Flow Router specific issue. I agree that it might be the wrong approach to provide a fix here if Flow Router is at fault by polluting the `window.history`.

Will close this in the meantime.

**Closed as completed by cfnelson** 2017-10-16 18:36 UTC
